import type { Lang } from '@mje/ui';

const COPY = {
  zh: {
    activities: '施工事项',
    add: '新增施工事项',
    area: '施工区域',
    package: '工作包／范围',
    process: '施工事项',
    output: '今日完成',
    material: '关联材料',
    actual: '实际耗料',
    estimate: '按安装量带入，待申报确认',
    edited: '人工填写，待申报确认',
    declared: '已申报，尚未独立核实',
    pending: '耗料待补报',
    difference: '差异说明（选填）',
    review: '完成量已变化，请检查实际耗料；现有用量已保留',
    submit: '确认并提交日报',
    submitHint:
      '提交将确认下列施工成果和已填写用料。标为待补报的耗料继续待补报。',
    noQuantity: '按完成情况记录，数量可留空',
    subtotal: '本日已申报耗料',
    unknownHistory:
      '本卡仅列本日申报耗料；累计请查看材料数量账。尚未建立数量账时，历史耗料仍未知。',
    delivery: '今日到货',
    rule: '按本事项完成量 1:1 带入',
    ruleHint: '仅用于已明确采用该比例的材料和施工范围',
    status: '完成情况',
    missing: '未填写',
    noMaterial: '不关联材料',
    work: '对应工作项',
    installation: '安装成果',
    predecessor: '前道工序完成量',
    supplement: '施工补充说明（选填）',
    adoptExisting: '新增安装事项将关联本项已填今日数量：',
  },
  en: {
    activities: 'Work activities',
    add: 'Add activity',
    area: 'Work area',
    package: 'Work package / scope',
    process: 'Activity',
    output: 'Completed today',
    material: 'Linked material',
    actual: 'Actual consumption',
    estimate: 'Carried from output; awaiting declaration',
    edited: 'Manually entered; awaiting declaration',
    declared: 'Declared; not independently verified',
    pending: 'Consumption pending',
    difference: 'Difference explanation (optional)',
    review:
      'Output changed. Review actual consumption; the entered amount is retained.',
    submit: 'Confirm and submit daily report',
    submitHint:
      'Submission confirms the listed output and entered consumption. Consumption marked pending stays pending.',
    noQuantity: 'Record completion; quantity may be blank',
    subtotal: 'Declared consumption today',
    unknownHistory:
      'This card lists today’s declaration only. See the material quantity ledger for cumulative use. Without a ledger, historical consumption remains unknown.',
    delivery: 'Arrived today',
    rule: 'Carry 1:1 from this activity’s output',
    ruleHint: 'Use only for a material and scope with an established ratio',
    status: 'Completion',
    missing: 'Not filled',
    noMaterial: 'No linked material',
    work: 'Work item',
    installation: 'Installation output',
    predecessor: 'Process quantity',
    supplement: 'Additional construction notes (optional)',
    adoptExisting: 'New installation activity adopts the existing quantity: ',
  },
  sr: {
    activities: 'Građevinske aktivnosti',
    add: 'Dodaj aktivnost',
    area: 'Područje radova',
    package: 'Radni paket / obim',
    process: 'Aktivnost',
    output: 'Izvedeno danas',
    material: 'Povezani materijal',
    actual: 'Stvarna potrošnja',
    estimate: 'Preneto iz izvedene količine; čeka potvrdu prijave',
    edited: 'Ručno uneto; čeka potvrdu prijave',
    declared: 'Prijavljeno; nije nezavisno provereno',
    pending: 'Potrošnja čeka dopunu',
    difference: 'Objašnjenje razlike (opciono)',
    review:
      'Izvedena količina je promenjena. Proverite potrošnju; uneta količina je sačuvana.',
    submit: 'Potvrdi i predaj dnevni izveštaj',
    submitHint:
      'Predaja potvrđuje navedene radove i unetu potrošnju. Potrošnja označena za dopunu ostaje na čekanju.',
    noQuantity: 'Opišite izvedene radove; količina može ostati prazna',
    subtotal: 'Prijavljena potrošnja danas',
    unknownHistory:
      'Kartica prikazuje samo današnju prijavu. Ukupnu potrošnju pogledajte u količinskoj evidenciji materijala. Bez evidencije, ranija potrošnja ostaje nepoznata.',
    delivery: 'Danas pristiglo',
    rule: 'Prenesi 1:1 iz količine ove aktivnosti',
    ruleHint: 'Samo za materijal i obim sa utvrđenim odnosom',
    status: 'Izvedeni radovi',
    missing: 'Nije popunjeno',
    noMaterial: 'Nema povezanog materijala',
    work: 'Radna stavka',
    installation: 'Rezultat montaže',
    predecessor: 'Količina prethodne faze',
    supplement: 'Dodatne napomene o radovima (opciono)',
    adoptExisting: 'Nova montažna aktivnost preuzima unetu današnju količinu: ',
  },
  es: {
    activities: 'Actividades de obra',
    add: 'Añadir actividad',
    area: 'Zona de trabajo',
    package: 'Paquete de trabajo / alcance',
    process: 'Actividad',
    output: 'Realizado hoy',
    material: 'Material vinculado',
    actual: 'Consumo real',
    estimate:
      'Traído de la cantidad ejecutada; pendiente de confirmar declaración',
    edited: 'Introducido manualmente; pendiente de confirmar declaración',
    declared: 'Declarado; sin verificación independiente',
    pending: 'Consumo pendiente',
    difference: 'Explicación de la diferencia (opcional)',
    review:
      'La cantidad ejecutada cambió. Revise el consumo; se conserva la cantidad introducida.',
    submit: 'Confirmar y enviar parte diario',
    submitHint:
      'El envío confirma la ejecución y el consumo introducido indicados. El consumo marcado como pendiente sigue pendiente.',
    noQuantity: 'Describa el trabajo realizado; la cantidad puede quedar vacía',
    subtotal: 'Consumo declarado hoy',
    unknownHistory:
      'La tarjeta muestra solo la declaración de hoy. Consulte el registro de materiales para el consumo acumulado. Sin registro, el consumo histórico sigue siendo desconocido.',
    delivery: 'Recibido hoy',
    rule: 'Traer 1:1 de la cantidad de esta actividad',
    ruleHint: 'Solo para material y alcance con proporción establecida',
    status: 'Trabajo realizado',
    missing: 'Sin completar',
    noMaterial: 'Sin material vinculado',
    work: 'Partida de trabajo',
    installation: 'Resultado de instalación',
    predecessor: 'Cantidad de etapa previa',
    supplement: 'Notas adicionales de obra (opcional)',
    adoptExisting:
      'La nueva actividad de instalación usa la cantidad ya introducida hoy: ',
  },
} as const;

export const activityText = (lang: Lang) => COPY[lang];
