import type { Lang } from '@mje/ui';
const zh = {
  followupUnavailable:
    '当前跟进问题未能加载，请刷新后再关联；日报原版本保持不变。',
  reversal: '待撤回旧申报扣减；旧量仍在账，当前耗用待核',
  reverseSelect: '选择撤回旧扣减',
  invalidInput:
    '填写内容不符合要求，请检查后再保存；尚未保存的期初输入已保留。',
  title: '现场材料数量账',
  current: '按当前有效记录',
  opening: '本日期初',
  use: '今日已纳入耗用',
  total: '累计已纳入耗用',
  balance: '账内结存',
  ofOpening: '占有依据期初',
  openingLimit:
    '仅支持有依据的期初日余额，不要求半夜现场盘点。午间盘点原时刻不能改成零点；若无法分割当日收发，本片尚不支持以该盘点接管数量账。',
  basis: '期初依据',
  scope: '规格／所有权／保管范围',
  pending: '收发记录尚未完整；账存不代表实际可用量',
  declared: '据申报入账，尚未独立核实',
  frozen: '日报当时摘要',
  missing: '该版本未记录材料数量账',
  history: '材料账历史（不改旧日报）',
  ready: '待纳入',
  included: '已纳入',
  correction: '更正待处理，旧量仍在账',
  unknown: '数量待核，未纳入',
  sources: '来源及耗用差异',
  difference: '耗用差异',
  cause: '原因待查',
  noDifference: '无数量差异',
  differenceUnknown: '差异未知',
  cumulativeArrivals: '系统累计到货',
  followup: '跟进责任与期限',
  followupRequired:
    '差异原因未知：须关联有负责人及期限的跟进问题，入账不代表原因已解决。',
  none: '暂无期初数量账',
  setup: '建立有依据期初',
  quantity: '期初数量',
  ownership: '所有权',
  custody: '保管责任',
  location: '存放地点',
  date: '期初业务日',
  cutoff: '期初日零点（含工地时区）',
  save: '保存期初',
  select: '选择纳入',
  confirm: '确认处理选中记录',
  admit: '确认更新材料账',
  cancel: '取消',
  issue: '关联已有跟进问题（选填）',
  due: '跟进期限（来自问题模块）',
  noIssue: '不关联问题',
  retry: '重试原操作',
  refresh: '刷新',
  discard: '放弃重试并刷新',
  unsettled: '结果未知，保留原操作；请重试或刷新',
  immutable: '纳入只更新材料账；日报须通过原提交／更正流程才生成版本',
  record: '日报来源',
  output: '安装成果',
  actual: '申报耗料',
};
const en = {
  followupUnavailable:
    'Current follow-ups could not be loaded. Refresh before linking; the report revision stays unchanged.',
  reversal: 'Reversal pending; prior deduction remains, current use unknown',
  reverseSelect: 'Select reversal of prior deduction',
  invalidInput:
    'Check the values and save again. Unsaved opening inputs are retained.',
  followupRequired:
    'Unknown variance cause: link a follow-up with an owner and deadline. Admission does not resolve its cause.',
  title: 'Site material quantity ledger',
  current: 'Current effective records',
  opening: 'Opening today',
  use: 'Admitted use today',
  total: 'Cumulative admitted use',
  balance: 'Book balance',
  ofOpening: 'of documented opening',
  openingLimit:
    'Use an evidenced start-of-day balance; no midnight physical count is required. Keep the actual time of a midday count. This slice cannot take over from that count when same-day receipts/use cannot be separated.',
  basis: 'Opening basis',
  scope: 'Specification / ownership / custody',
  pending:
    'Receipts and use are incomplete; book balance is not available stock',
  declared: 'Admitted from declaration; not independently verified',
  frozen: 'At daily report submission',
  missing: 'This revision did not record a material ledger',
  history: 'Ledger history (reports stay unchanged)',
  ready: 'Awaiting admission',
  included: 'Admitted',
  correction: 'Correction pending; prior quantity remains in ledger',
  unknown: 'Quantity pending; excluded',
  sources: 'Sources and consumption differences',
  difference: 'Consumption difference',
  cause: 'Cause awaiting investigation',
  noDifference: 'No quantity difference',
  differenceUnknown: 'Difference unknown',
  cumulativeArrivals: 'System cumulative arrivals',
  followup: 'Responsible person and due time',
  none: 'No documented opening ledger',
  setup: 'Establish documented opening',
  quantity: 'Opening quantity',
  ownership: 'Ownership',
  custody: 'Custodian',
  location: 'Storage location',
  date: 'Opening business date',
  cutoff: 'Opening day midnight (site timezone)',
  save: 'Save opening',
  select: 'Select for admission',
  confirm: 'Confirm selected records',
  admit: 'Confirm ledger update',
  cancel: 'Cancel',
  issue: 'Link existing follow-up (optional)',
  due: 'Due instant (with timezone)',
  noIssue: 'No linked issue',
  retry: 'Retry original operation',
  refresh: 'Refresh',
  discard: 'Stop retrying and refresh',
  unsettled: 'Outcome unknown; original operation retained. Retry or refresh.',
  immutable:
    'Admission changes the ledger only. A report revision requires the normal submit/correction action.',
  record: 'Report source',
  output: 'Installed output',
  actual: 'Declared consumption',
};
const sr = {
  followupUnavailable:
    'Trenutna praćenja nisu učitana. Osvežite pre povezivanja; verzija izveštaja ostaje ista.',
  reversal: 'Čeka storniranje prethodne potrošnje; nova količina nije poznata',
  reverseSelect: 'Izaberi storniranje prethodne potrošnje',
  invalidInput:
    'Proverite vrednosti i sačuvajte ponovo. Neupisani početni podaci su sačuvani u obrascu.',
  followupRequired:
    'Nepoznat uzrok razlike: povežite praćenje sa odgovornom osobom i rokom. Knjiženje ne rešava uzrok.',
  title: 'Količinska evidencija materijala',
  current: 'Trenutno važeći zapisi',
  opening: 'Početno stanje dana',
  use: 'Uključena potrošnja danas',
  total: 'Ukupna uključena potrošnja',
  balance: 'Knjigovodstveno stanje',
  ofOpening: 'dokumentovanog početnog stanja',
  openingLimit:
    'Koristite potkrepljeno stanje na početku dana; fizički popis u ponoć nije potreban. Sačuvajte stvarno vreme dnevnog popisa. Preuzimanje tog popisa nije podržano ako se dnevni prijem i potrošnja ne mogu odvojiti.',
  basis: 'Osnov početnog stanja',
  scope: 'Specifikacija / vlasništvo / čuvanje',
  pending: 'Prijem i potrošnja nisu potpuni; stanje nije raspoloživa zaliha',
  declared: 'Uključeno na osnovu prijave; nije nezavisno provereno',
  frozen: 'Pri predaji dnevnog izveštaja',
  missing: 'Ova verzija nema evidenciju materijala',
  history: 'Istorija evidencije (izveštaji ostaju isti)',
  ready: 'Čeka uključivanje',
  included: 'Uključeno',
  correction: 'Ispravka čeka; prethodna količina ostaje',
  unknown: 'Količina čeka proveru; nije uključena',
  sources: 'Izvori i razlike u potrošnji',
  difference: 'Razlika u potrošnji',
  cause: 'Uzrok se istražuje',
  noDifference: 'Nema količinske razlike',
  differenceUnknown: 'Razlika nije poznata',
  cumulativeArrivals: 'Ukupno evidentirani prijem',
  followup: 'Odgovorna osoba i rok',
  none: 'Nema dokumentovanog početnog stanja',
  setup: 'Unesi dokumentovano početno stanje',
  quantity: 'Početna količina',
  ownership: 'Vlasništvo',
  custody: 'Odgovoran za čuvanje',
  location: 'Mesto skladištenja',
  date: 'Početni poslovni dan',
  cutoff: 'Ponoć početnog dana (zona gradilišta)',
  save: 'Sačuvaj početno stanje',
  select: 'Izaberi za uključivanje',
  confirm: 'Potvrdi izabrane zapise',
  admit: 'Potvrdi ažuriranje evidencije',
  cancel: 'Otkaži',
  issue: 'Poveži postojeći zadatak (opciono)',
  due: 'Rok (sa vremenskom zonom)',
  noIssue: 'Bez povezanog zadatka',
  retry: 'Ponovi originalnu radnju',
  refresh: 'Osveži',
  discard: 'Prekini ponavljanje i osveži',
  unsettled: 'Ishod nije poznat; originalna radnja je sačuvana.',
  immutable:
    'Uključivanje menja samo evidenciju. Nova verzija izveštaja zahteva uobičajenu predaju ili ispravku.',
  record: 'Izvorni izveštaj',
  output: 'Montirano',
  actual: 'Prijavljena potrošnja',
};
const es = {
  followupUnavailable:
    'No se cargaron los seguimientos actuales. Actualice antes de vincular; la revisión permanece intacta.',
  reversal:
    'Reversión pendiente; permanece el descuento anterior, consumo actual desconocido',
  reverseSelect: 'Seleccionar reversión del descuento anterior',
  invalidInput:
    'Revise los valores y vuelva a guardar. Los datos iniciales sin guardar se conservan.',
  followupRequired:
    'Causa de diferencia desconocida: vincule un seguimiento con responsable y plazo. Registrar no resuelve la causa.',
  title: 'Registro de cantidades de materiales',
  current: 'Registros vigentes',
  opening: 'Existencia inicial del día',
  use: 'Consumo incorporado hoy',
  total: 'Consumo incorporado acumulado',
  balance: 'Saldo contable',
  ofOpening: 'del saldo inicial documentado',
  openingLimit:
    'Use un saldo documentado al inicio del día; no exige contar físicamente a medianoche. Conserve la hora real del conteo diurno. Este alcance no permite partir de ese conteo si no se separan las entradas y consumos del mismo día.',
  basis: 'Base de existencia inicial',
  scope: 'Especificación / propiedad / custodia',
  pending:
    'Entradas y consumos incompletos; el saldo no garantiza disponibilidad',
  declared: 'Incorporado según declaración; sin verificación independiente',
  frozen: 'Al presentar el informe diario',
  missing: 'Esta revisión no registró materiales',
  history: 'Historial del registro (informes sin cambios)',
  ready: 'Pendiente de incorporar',
  included: 'Incorporado',
  correction: 'Corrección pendiente; se mantiene la cantidad anterior',
  unknown: 'Cantidad pendiente; excluida',
  sources: 'Fuentes y diferencias de consumo',
  difference: 'Diferencia de consumo',
  cause: 'Causa pendiente de investigar',
  noDifference: 'Sin diferencia de cantidad',
  differenceUnknown: 'Diferencia desconocida',
  cumulativeArrivals: 'Llegadas acumuladas del sistema',
  followup: 'Responsable y plazo',
  none: 'Sin existencia inicial documentada',
  setup: 'Establecer existencia inicial documentada',
  quantity: 'Cantidad inicial',
  ownership: 'Propiedad',
  custody: 'Responsable de custodia',
  location: 'Ubicación',
  date: 'Fecha inicial',
  cutoff: 'Medianoche del día inicial (zona de obra)',
  save: 'Guardar existencia inicial',
  select: 'Seleccionar para incorporar',
  confirm: 'Confirmar registros seleccionados',
  admit: 'Confirmar actualización del registro',
  cancel: 'Cancelar',
  issue: 'Vincular seguimiento existente (opcional)',
  due: 'Plazo (con zona)',
  noIssue: 'Sin incidencia vinculada',
  retry: 'Reintentar operación original',
  refresh: 'Actualizar',
  discard: 'Dejar de reintentar y actualizar',
  unsettled: 'Resultado desconocido; se conserva la operación original.',
  immutable:
    'La incorporación solo cambia el registro. Una revisión requiere presentar o corregir el informe.',
  record: 'Informe de origen',
  output: 'Instalado',
  actual: 'Consumo declarado',
};
export const materialContinuityCopy = (lang: Lang): typeof zh =>
  ({ zh, en, sr, es })[lang];
